export const mid_products_22 = [
  {
    id: 1,
    title: 'Emperor Bed',
    price: 21.99,
    category: 'Liddy',
    img: './images/product-1.jpg',
    remote_img: '',
  },
  {
    id: 2,
    title: 'Accent Chair',
    price: 25.99,
    category: 'Caressa',
    img: './images/product-2.jpg',
    remote_img: '',
  },
  {
    id: 3,
    title: 'High-Back Bench',
    price: 9.99,
    category: 'Ikea',
    img: './images/product-3.jpg',
    remote_img: '',
  },
  {
    id: 4,
    title: 'Wooden Table',
    price: 19.99,
    category: 'Ikea',
    img: './images/product-4.jpg',
    remote_img: '',
  },
];

export const products_22 = [
  {
    id: 1,
    title: 'Emperor Bed',
    price: 21.99,
    category: 'Liddy',
    img: './images/product-1.jpg',
    remote_img: '',
  },
  {
    id: 2,
    title: 'Accent Chair',
    price: 25.99,
    category: 'Caressa',
    img: './images/product-2.jpg',
    remote_img: '',
  },
  {
    id: 3,
    title: 'High-Back Bench',
    price: 9.99,
    category: 'Ikea',
    img: './images/product-3.jpg',
    remote_img: '',
  },
  {
    id: 4,
    title: 'Wooden Table',
    price: 19.99,
    category: 'Ikea',
    img: './images/product-4.jpg',
    remote_img: '',
  },
  {
    id: 5,
    title: 'Dining Table',
    price: 6.99,
    category: 'Caressa',
    img: './images/product-5.jpg',
    remote_img: '',
  },
  {
    id: 6,
    title: 'Entertainmint Center',
    price: 69.99,
    category: 'Liddy',
    img: './images/product-6.jpg',
    remote_img: '',
  },
  {
    id: 7,
    title: 'Albany Sectional',
    price: 10.99,
    category: 'Ikea',
    img: './images/product-7.jpg',
    remote_img: '',
  },
  {
    id: 8,
    title: 'Sofa Set',
    price: 69.99,
    category: 'Liddy',
    img: './images/product-8.jpg',
    remote_img: '',
  },
  {
    id: 9,
    title: 'Utopia Sofa',
    price: 69.99,
    category: 'Liddy',
    img: './images/product-9.jpg',
    remote_img: '',
  },
  {
    id: 10,
    title: 'Modern Bookshelf',
    price: 8.99,
    category: 'Marcos',
    img: './images/product-10.jpg',
    remote_img: '',
  },
  {
    id: 11,
    title: 'Albany Table',
    price: 79.99,
    category: 'Marcos',
    img: './images/product-11.jpg',
    remote_img: '',
  },
  {
    id: 12,
    title: 'Leather Sofa',
    price: 39.95,
    category: 'Liddy',
    img: './images/product-12.jpg',
    remote_img: '',
  },
];
