const menu = [
    {
      id: 1,
      title: 'eggs',
      category: 'breakfast',
      price: 12.59,
      img: './images/my-1.jpg',
      remote_img: '',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam dolores ut iusto quas quia dignissimos ullam. Enim voluptas, expedita architecto, cupiditate molestias quisquam error quam blanditiis tempore quo dicta. Ipsa.',
    },
    {
      id: 2,
      title: 'big salad ',
      category: 'lunch',
      price: 12.59,
      img: './images/my-2.jpg',
      remote_img: '',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam dolores ut iusto quas quia dignissimos ullam. Enim voluptas, expedita architecto, cupiditate molestias quisquam error quam blanditiis tempore quo dicta. Ipsa.',
    },
    {
      id: 3,
      title: 'fried dish',
      category: 'dinner',
      price: 12.59,
      img: './images/my-3.jpg',
      remote_img: '',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam dolores ut iusto quas quia dignissimos ullam. Enim voluptas, expedita architecto, cupiditate molestias quisquam error quam blanditiis tempore quo dicta. Ipsa.',
    },
    {
      id: 4,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.59,
      img: './images/item-1.jpeg',
      remote_img: '',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam dolores ut iusto quas quia dignissimos ullam. Enim voluptas, expedita architecto, cupiditate molestias quisquam error quam blanditiis tempore quo dicta. Ipsa.',
    },
    {
      id: 5,
      title: 'dinner double',
      category: 'dessert',
      price: 13.99,
      img: './images/item-2.jpeg',
      remote_img: '',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam dolores ut iusto quas quia dignissimos ullam. Enim voluptas, expedita architecto, cupiditate molestias quisquam error quam blanditiis tempore quo dicta. Ipsa.',
    },
    {
      id: 6,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 13.99,
      img: './images/item-3.jpeg',
      remote_img: '',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam dolores ut iusto quas quia dignissimos ullam. Enim voluptas, expedita architecto, cupiditate molestias quisquam error quam blanditiis tempore quo dicta. Ipsa.',
    },
  ];
  
  export default menu;